/**
 * DMC embroidery floss colors - subset for photo-to-pattern conversion
 * Full list: 400+ colors. This subset covers common ranges.
 * Source: DMC color charts, pixel-stitch.net
 */

export type DmcColor = {
  code: string;
  name: string;
  hex: string;
};

// Subset of ~100 common DMC colors spanning the spectrum
// Format: DMC code, name, hex. Extended set can be added later.
export const DMC_COLORS: DmcColor[] = [
  { code: "B5200", name: "Snow White", hex: "#FFFFFF" },
  { code: "310", name: "Black", hex: "#000000" },
  { code: "317", name: "Pewter Gray", hex: "#6B6B6B" },
  { code: "318", name: "Steel Gray Lt", hex: "#B0B0B0" },
  { code: "319", name: "Pistachio Green Vy Lt", hex: "#DEEBD0" },
  { code: "320", name: "Pistachio Green Med", hex: "#8DB36C" },
  { code: "321", name: "Christmas Red", hex: "#C41E3A" },
  { code: "322", name: "Baby Blue", hex: "#5D9FD4" },
  { code: "326", name: "Rose Very Dark", hex: "#922E3B" },
  { code: "333", name: "Blue Violet Dark", hex: "#5B407A" },
  { code: "334", name: "Baby Blue Medium", hex: "#5D9FD4" },
  { code: "335", name: "Rose", hex: "#EE6B6B" },
  { code: "340", name: "Blue Violet Medium", hex: "#7B6D9E" },
  { code: "341", name: "Blue Violet Light", hex: "#A5A5C6" },
  { code: "347", name: "Salmon Dark", hex: "#BF3939" },
  { code: "349", name: "Coral Dark", hex: "#CD3333" },
  { code: "350", name: "Coral Medium", hex: "#E75554" },
  { code: "351", name: "Coral", hex: "#F7786B" },
  { code: "352", name: "Coral Light", hex: "#FF9D8E" },
  { code: "355", name: "Terra Cotta Dark", hex: "#C45A3C" },
  { code: "356", name: "Terra Cotta Med", hex: "#E0724E" },
  { code: "367", name: "Pistachio Green Dk", hex: "#698B3B" },
  { code: "368", name: "Pistachio Green Lt", hex: "#B8CC96" },
  { code: "369", name: "Pistachio Green Vy Lt", hex: "#DEEBD0" },
  { code: "370", name: "Mustard Medium", hex: "#C49E2C" },
  { code: "371", name: "Mustard", hex: "#C49E2C" },
  { code: "372", name: "Mustard Lt", hex: "#D4A84B" },
  { code: "400", name: "Mahogany Dark", hex: "#6B2A0E" },
  { code: "402", name: "Mahogany Vy Lt", hex: "#F5A872" },
  { code: "407", name: "Desert Sand Med", hex: "#C48E6A" },
  { code: "413", name: "Pewter Gray Dark", hex: "#5B5B5B" },
  { code: "414", name: "Steel Gray Dk", hex: "#8A8A8A" },
  { code: "415", name: "Pearl Gray", hex: "#C9C9C9" },
  { code: "420", name: "Hazelnut Brown Dk", hex: "#8B6914" },
  { code: "422", name: "Hazelnut Brown Lt", hex: "#C4975C" },
  { code: "433", name: "Brown Med", hex: "#7B5C3C" },
  { code: "434", name: "Brown Light", hex: "#9B7D5C" },
  { code: "435", name: "Brown Vy Lt", hex: "#B8956C" },
  { code: "436", name: "Tan", hex: "#CD9B62" },
  { code: "437", name: "Tan Light", hex: "#E5B873" },
  { code: "444", name: "Lemon Dark", hex: "#F7C718" },
  { code: "445", name: "Lemon Light", hex: "#FFE666" },
  { code: "451", name: "Shell Gray Dark", hex: "#8B7B6B" },
  { code: "452", name: "Shell Gray Med", hex: "#A09080" },
  { code: "453", name: "Shell Gray Light", hex: "#C9B9A9" },
  { code: "469", name: "Avocado Green", hex: "#7B8B4A" },
  { code: "470", name: "Avocado Grn Lt", hex: "#9BAB6A" },
  { code: "471", name: "Avocado Grn Vy Lt", hex: "#B8C484" },
  { code: "472", name: "Avocado Grn U Lt", hex: "#D4E4A4" },
  { code: "498", name: "Christmas Red Dark", hex: "#9B1020" },
  { code: "500", name: "Blue Green Very Dark", hex: "#0B5B4A" },
  { code: "501", name: "Blue Green Dark", hex: "#2B7B6A" },
  { code: "502", name: "Blue Green", hex: "#3B9B8A" },
  { code: "503", name: "Blue Green Med", hex: "#5BB3A2" },
  { code: "504", name: "Blue Green Vy Lt", hex: "#97D4C8" },
  { code: "517", name: "Wedgwood Dark", hex: "#3B7B9B" },
  { code: "518", name: "Wedgwood Light", hex: "#6BA3C3" },
  { code: "519", name: "Sky Blue", hex: "#8BC3E3" },
  { code: "520", name: "Fern Green Dark", hex: "#5B7B4A" },
  { code: "522", name: "Fern Green", hex: "#7B9B6A" },
  { code: "523", name: "Fern Green Lt", hex: "#9BBB8A" },
  { code: "524", name: "Fern Green Vy Lt", hex: "#B8D4A4" },
  { code: "535", name: "Ash Gray Vy Lt", hex: "#6B6B6B" },
  { code: "543", name: "Beige Brown Vy Lt", hex: "#F7E7CE" },
  { code: "550", name: "Violet Very Dark", hex: "#5B3078" },
  { code: "552", name: "Violet Medium", hex: "#8B6BA3" },
  { code: "553", name: "Violet", hex: "#9B7BB3" },
  { code: "554", name: "Violet Light", hex: "#C9A3D4" },
  { code: "561", name: "Chartreuse Vy Dk", hex: "#5B8B20" },
  { code: "562", name: "Chartreuse Med", hex: "#7BAB40" },
  { code: "563", name: "Chartreuse Light", hex: "#A3CB60" },
  { code: "564", name: "Chartreuse Vy Lt", hex: "#C9E380" },
  { code: "581", name: "Moss Green", hex: "#8B9B4A" },
  { code: "597", name: "Turquoise", hex: "#5BA3A3" },
  { code: "598", name: "Turquoise Light", hex: "#8BC3C3" },
  { code: "600", name: "Cranberry Very Dark", hex: "#CD2B4A" },
  { code: "601", name: "Cranberry Dark", hex: "#CD2B4A" },
  { code: "602", name: "Cranberry Medium", hex: "#E35B73" },
  { code: "603", name: "Cranberry", hex: "#F7788E" },
  { code: "604", name: "Cranberry Light", hex: "#FF9DAA" },
  { code: "605", name: "Cranberry Vy Lt", hex: "#FFB3BD" },
  { code: "618", name: "Tan", hex: "#B78B5C" },
  { code: "619", name: "Tan Light", hex: "#CD9B73" },
  { code: "620", name: "Tan Very Light", hex: "#E5B38B" },
  { code: "621", name: "Tan Ultra Very Lt", hex: "#F5C9A3" },
  { code: "666", name: "Christmas Red Bright", hex: "#CD2B2B" },
  { code: "676", name: "Old Gold Light", hex: "#E5B840" },
  { code: "677", name: "Old Gold Vy Lt", hex: "#F5D480" },
  { code: "680", name: "Old Gold Dark", hex: "#B39320" },
  { code: "699", name: "Christmas Green", hex: "#0F8644" },
  { code: "700", name: "Christmas Green Bright", hex: "#0F7B3B" },
  { code: "701", name: "Christmas Green Lt", hex: "#2B9B5A" },
  { code: "702", name: "Kelly Green", hex: "#2BAB5A" },
  { code: "703", name: "Chartreuse", hex: "#7BAB3B" },
  { code: "704", name: "Chartreuse Bright", hex: "#9BBB2B" },
  { code: "712", name: "Cream", hex: "#FFFBEA" },
  { code: "718", name: "Plum", hex: "#9B4A7B" },
  { code: "720", name: "Orange Spice Dark", hex: "#E5722B" },
  { code: "721", name: "Orange Spice Med", hex: "#F78B3B" },
  { code: "722", name: "Orange Spice Light", hex: "#F7A353" },
  { code: "725", name: "Topaz", hex: "#FFC73B" },
  { code: "726", name: "Topaz Light", hex: "#FFD966" },
  { code: "727", name: "Topaz Vy Lt", hex: "#FFE699" },
  { code: "729", name: "Old Gold Medium", hex: "#D4A840" },
  { code: "730", name: "Olive Green V Dk", hex: "#6B7B2B" },
  { code: "731", name: "Olive Green Dk", hex: "#6B7B2B" },
  { code: "732", name: "Olive Green", hex: "#8B9B4A" },
  { code: "733", name: "Olive Green Med", hex: "#A3AB6A" },
  { code: "734", name: "Olive Green Lt", hex: "#B8B87B" },
  { code: "738", name: "Tan Very Light", hex: "#E5B38B" },
  { code: "739", name: "Tan Ultra Very Lt", hex: "#F5D4B3" },
  { code: "740", name: "Tangerine", hex: "#FF8B2B" },
  { code: "741", name: "Tangerine Med", hex: "#FF9B4A" },
  { code: "742", name: "Tangerine Light", hex: "#FFB366" },
  { code: "743", name: "Yellow Med", hex: "#FFE066" },
  { code: "744", name: "Yellow Pale", hex: "#FFE580" },
  { code: "745", name: "Yellow Pale Lt", hex: "#FFE899" },
  { code: "746", name: "Off White", hex: "#FFFBE6" },
  { code: "747", name: "Sky Blue Vy Lt", hex: "#D4EEF5" },
  { code: "754", name: "Peach Light", hex: "#F7C9B8" },
  { code: "758", name: "Terra Cotta Vy Lt", hex: "#E5A38B" },
  { code: "760", name: "Salmon", hex: "#F5A393" },
  { code: "761", name: "Salmon Light", hex: "#FFC4B8" },
  { code: "762", name: "Pearl Gray Vy Lt", hex: "#E5E5E5" },
  { code: "772", name: "Yellow Green Vy Lt", hex: "#E5F5B8" },
  { code: "775", name: "Baby Blue Vy Lt", hex: "#E5F0FF" },
  { code: "776", name: "Pink Medium", hex: "#F5A3B8" },
  { code: "778", name: "Antique Mauve Vy Lt", hex: "#E5B8C4" },
  { code: "779", name: "Cocoa Dark", hex: "#8B7B6B" },
  { code: "780", name: "Topaz Ultra Vy Dk", hex: "#9B7B20" },
  { code: "781", name: "Topaz Very Dark", hex: "#B39330" },
  { code: "782", name: "Topaz Dark", hex: "#CDAB40" },
  { code: "783", name: "Topaz Medium", hex: "#E5C453" },
  { code: "791", name: "Cornflower Blue Vy Dk", hex: "#2B4A8B" },
  { code: "794", name: "Cornflower Blue Dk", hex: "#4A6BA3" },
  { code: "795", name: "Cornflower Blue Med", hex: "#7B9BC9" },
  { code: "796", name: "Cornflower Blue", hex: "#8BA3D4" },
  { code: "797", name: "Cornflower Blue Lt", hex: "#B8C9F0" },
  { code: "798", name: "Cornflower Blue Vy Lt", hex: "#D4E0F5" },
  { code: "799", name: "Royal Blue", hex: "#4A6BA3" },
  { code: "800", name: "Delft Blue Pale", hex: "#C9D4E5" },
  { code: "806", name: "Delft Blue Dark", hex: "#4A6B9B" },
  { code: "807", name: "Delft Blue", hex: "#6B8BB8" },
  { code: "809", name: "Delft Blue Light", hex: "#9BB3D4" },
  { code: "813", name: "Blue Light", hex: "#8BA3C9" },
  { code: "814", name: "Garnet Dark", hex: "#8B2038" },
  { code: "815", name: "Garnet Medium", hex: "#A32B4A" },
  { code: "816", name: "Garnet", hex: "#B83B5A" },
  { code: "817", name: "Coral Red Very Dark", hex: "#CD2B4A" },
  { code: "818", name: "Baby Pink", hex: "#FFE6EE" },
  { code: "819", name: "Baby Pink Light", hex: "#FFF0F5" },
  { code: "820", name: "Royal Blue Very Dark", hex: "#1A3B6B" },
  { code: "822", name: "Beige Gray Light", hex: "#E5E0D4" },
  { code: "823", name: "Navy Blue Dark", hex: "#20385B" },
  { code: "824", name: "Navy Blue Medium", hex: "#4A6B8B" },
  { code: "825", name: "Navy Blue Light", hex: "#6B8BA3" },
  { code: "826", name: "Blue Medium", hex: "#7BA3C9" },
  { code: "827", name: "Blue Very Light", hex: "#B8D4F0" },
  { code: "828", name: "Blue Ultra Very Lt", hex: "#E5F0FF" },
  { code: "829", name: "Golden Olive Vy Dk", hex: "#8B7B20" },
  { code: "830", name: "Golden Olive Dk", hex: "#A38B2B" },
  { code: "831", name: "Golden Olive Med", hex: "#B89B4A" },
  { code: "832", name: "Golden Olive", hex: "#C9AB5A" },
  { code: "833", name: "Golden Olive Lt", hex: "#D4C97B" },
  { code: "834", name: "Golden Olive Vy Lt", hex: "#E5DCA3" },
  { code: "838", name: "Beige Brown Dark", hex: "#6B5C4A" },
  { code: "839", name: "Beige Brown Med", hex: "#8B7B6B" },
  { code: "840", name: "Beige Brown Lt", hex: "#B8A89A" },
  { code: "841", name: "Beige Brown Vy Lt", hex: "#D4C4B8" },
  { code: "842", name: "Beige Brown Ultra Vy Lt", hex: "#E5D4C4" },
  { code: "844", name: "Beaver Gray Ultra Dk", hex: "#4A4A4A" },
  { code: "868", name: "Hazelnut Brown Vy Dk", hex: "#8B6B3B" },
  { code: "869", name: "Hazelnut Brown Vy Dk", hex: "#6B4A2B" },
  { code: "890", name: "Pistachio Green U Dk", hex: "#3B5C2B" },
  { code: "891", name: "Carnation Dark", hex: "#FF8BA3" },
  { code: "892", name: "Carnation Medium", hex: "#FFA3B8" },
  { code: "893", name: "Carnation Light", hex: "#FFB8C9" },
  { code: "894", name: "Carnation Very Light", hex: "#FFC9D4" },
  { code: "895", name: "Hunter Green Vy Dk", hex: "#2B5C3B" },
  { code: "898", name: "Coffee Brown Vy Dk", hex: "#6B4A3B" },
  { code: "899", name: "Coffee Brown Med", hex: "#A37B6B" },
  { code: "900", name: "Burnt Orange Dark", hex: "#D45320" },
  { code: "902", name: "Garnet Very Dark", hex: "#8B2038" },
  { code: "904", name: "Parrot Green Vy Dk", hex: "#5B8B3B" },
  { code: "905", name: "Parrot Green Dark", hex: "#7BAB5A" },
  { code: "906", name: "Parrot Green Med", hex: "#9BC97B" },
  { code: "907", name: "Parrot Green Lt", hex: "#B8E39B" },
  { code: "909", name: "Emerald Green Vy Dk", hex: "#2B7B5A" },
  { code: "910", name: "Emerald Green Dark", hex: "#3B9B73" },
  { code: "911", name: "Emerald Green Med", hex: "#4AB88A" },
  { code: "912", name: "Emerald Green Lt", hex: "#7BD4A3" },
  { code: "913", name: "Emerald Green Vy Lt", hex: "#A3E5C4" },
  { code: "915", name: "Plum Dark", hex: "#8B3B7B" },
  { code: "917", name: "Plum Medium", hex: "#9B5A8B" },
  { code: "918", name: "Red Copper Dark", hex: "#8B4A3B" },
  { code: "919", name: "Red Copper", hex: "#A35A4A" },
  { code: "920", name: "Copper Med", hex: "#C47B5A" },
  { code: "921", name: "Copper", hex: "#D49B73" },
  { code: "922", name: "Copper Light", hex: "#E5AB8B" },
  { code: "924", name: "Gray Green Vy Dk", hex: "#5B6B5A" },
  { code: "926", name: "Gray Green Med", hex: "#8B9B8B" },
  { code: "927", name: "Gray Green Light", hex: "#B8C4B8" },
  { code: "928", name: "Gray Green Vy Lt", hex: "#D4E0D4" },
  { code: "930", name: "Antique Blue Dark", hex: "#5B7B9B" },
  { code: "931", name: "Antique Blue Med", hex: "#7B9BB8" },
  { code: "932", name: "Antique Blue Light", hex: "#A3B8D4" },
  { code: "934", name: "Black Avocado Green", hex: "#3B4A2B" },
  { code: "935", name: "Avocado Green Dk", hex: "#4A5C3B" },
  { code: "936", name: "Avocado Grn V Dk", hex: "#5A6B4A" },
  { code: "937", name: "Avocado Green Med", hex: "#6B7B5A" },
  { code: "938", name: "Coffee Brown Ultra Dk", hex: "#4A3020" },
  { code: "939", name: "Navy Blue Very Dk", hex: "#1A2B4A" },
  { code: "943", name: "Aquamarine Med", hex: "#40B8A3" },
  { code: "945", name: "Tawny", hex: "#F7B88B" },
  { code: "946", name: "Burnt Orange Med", hex: "#E5723B" },
  { code: "947", name: "Burnt Orange", hex: "#FF8B4A" },
  { code: "948", name: "Peach Very Light", hex: "#FFE5D4" },
  { code: "950", name: "Desert Sand Light", hex: "#F0C4A3" },
  { code: "951", name: "Tawny Light", hex: "#FFD4B8" },
  { code: "954", name: "Nile Green", hex: "#7BC9A3" },
  { code: "955", name: "Nile Green Light", hex: "#A3E5C4" },
  { code: "956", name: "Geranium", hex: "#FF9BA3" },
  { code: "957", name: "Geranium Pale", hex: "#FFB8B8" },
  { code: "958", name: "Seafoam Green Dk", hex: "#5AC9A3" },
  { code: "959", name: "Seafoam Green Med", hex: "#7BE5B8" },
  { code: "961", name: "Dusty Rose Dark", hex: "#C97B8B" },
  { code: "962", name: "Dusty Rose Med", hex: "#E59BA3" },
  { code: "963", name: "Dusty Rose Ult Vy Lt", hex: "#FFD4D4" },
  { code: "964", name: "Seafoam Green Light", hex: "#A3F0D4" },
  { code: "966", name: "Baby Green Med", hex: "#B8E5C4" },
  { code: "967", name: "Apricot Very Light", hex: "#FFE5D4" },
  { code: "970", name: "Pumpkin Light", hex: "#F78B2B" },
  { code: "971", name: "Pumpkin", hex: "#F78B2B" },
  { code: "972", name: "Canary Deep", hex: "#FFB82B" },
  { code: "973", name: "Canary Bright", hex: "#FFD42B" },
  { code: "975", name: "Golden Brown Dk", hex: "#9B6B2B" },
  { code: "976", name: "Golden Brown Med", hex: "#C49B5A" },
  { code: "977", name: "Golden Brown Lt", hex: "#E5B87B" },
  { code: "986", name: "Forest Green Vy Dk", hex: "#3B5C3B" },
  { code: "987", name: "Forest Green Dk", hex: "#4A7B4A" },
  { code: "988", name: "Forest Green Med", hex: "#6B9B6B" },
  { code: "989", name: "Forest Green", hex: "#8BB88B" },
  { code: "991", name: "Aquamarine Dark", hex: "#3B9B8B" },
  { code: "992", name: "Aquamarine Light", hex: "#7BD4C9" },
  { code: "993", name: "Aquamarine Vy Lt", hex: "#A3E5E0" },
  { code: "995", name: "Electric Blue Dark", hex: "#2B8BC9" },
  { code: "996", name: "Electric Blue Med", hex: "#5AB3E5" },
  { code: "3011", name: "Khaki Green Dk", hex: "#7B8B5A" },
  { code: "3012", name: "Khaki Green Med", hex: "#9BAB7B" },
  { code: "3013", name: "Khaki Green Lt", hex: "#B8C49B" },
  { code: "3021", name: "Brown Gray Vy Dk", hex: "#5A5A4A" },
  { code: "3022", name: "Brown Gray Med", hex: "#8B8B73" },
  { code: "3023", name: "Brown Gray Light", hex: "#B8B8A3" },
  { code: "3024", name: "Brown Gray Vy Lt", hex: "#D4D4C4" },
  { code: "3031", name: "Mocha Brown Vy Dk", hex: "#4A3B2B" },
  { code: "3032", name: "Mocha Brown Med", hex: "#9B8B73" },
  { code: "3033", name: "Mocha Brown Vy Lt", hex: "#E0D4C4" },
  { code: "3041", name: "Antique Violet Med", hex: "#8B7BA3" },
  { code: "3042", name: "Antique Violet Light", hex: "#B8A8C9" },
  { code: "3045", name: "Yellow Beige Lt", hex: "#F5E5C9" },
  { code: "3046", name: "Yellow Beige Med", hex: "#E5D4A3" },
  { code: "3047", name: "Yellow Beige Dk", hex: "#D4C49B" },
  { code: "3051", name: "Green Gray Dk", hex: "#6B7B6B" },
  { code: "3052", name: "Green Gray Med", hex: "#9BAB9B" },
  { code: "3053", name: "Green Gray", hex: "#B8C4B8" },
];

/**
 * Find nearest DMC color by RGB distance (Euclidean in RGB space)
 */
export function nearestDmcColor(r: number, g: number, b: number): DmcColor {
  let best = DMC_COLORS[0];
  let bestDist = Number.POSITIVE_INFINITY;

  for (const dmc of DMC_COLORS) {
    const hex = dmc.hex.replace("#", "");
    const dr = parseInt(hex.slice(0, 2), 16) - r;
    const dg = parseInt(hex.slice(2, 4), 16) - g;
    const db = parseInt(hex.slice(4, 6), 16) - b;
    const dist = dr * dr + dg * dg + db * db;
    if (dist < bestDist) {
      bestDist = dist;
      best = dmc;
    }
  }
  return best;
}
